# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Install SonarCloud
          command: |
            dotnet tool install --global dotnet-sonarscanner
            export PATH="$PATH:/root/.dotnet/tools"
      - run:
          name: Restore packages
          command:
            dotnet restore
      - run:
          name: Start SonarCloud scanner
          command:
            dotnet-sonarscanner begin /k:"ar3cka_domainator"
      - run:
          name: Build
          command:
            dotnet build
      - run:
          name: Test
          command:
            dotnet test
      - run:
          name: Stop SonarCloud scanner
          command:
            dotnet-sonarscanner end
  
workflows:
  version: 2
  build-package:
    jobs:
      - build:
          context: SonarCloud
