# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Install SonarCloud
          command: |
            apt-get update && apt-get install -y openjdk-11-jre
            dotnet tool install --global dotnet-sonarscanner
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet sonarscanner begin /k:"ar3cka_domainator" /d:sonar.host.url=https://sonarcloud.io /o:ar3cka /d:sonar.login=$SONAR_TOKEN
      - run:
          name: Build
          command: |
            dotnet build -c=Release
            dotnet test --no-build -c:Release
      - run:
          name: Test
          command: |
            dotnet test --no-build -c:Release
      - run:
          name: Publish results to SonarCloud
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
  
workflows:
  version: 2
  build-package:
    jobs:
      - build:
          context: SonarCloud
