# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1.102-bionic
      - image: circleci/dynamodb
    environment:
        AWS_ACCESS_KEY_ID: FOO
        AWS_SECRET_ACCESS_KEY: FOO
        AWS_REGION: FOO
    steps:
      - checkout
      - jq/install
      - run:
         name: Install GitVersion
         command: |
             export GITVERSION_VERSION="5.2.4"
             dotnet tool install --global GitVersion.Tool --version $GITVERSION_VERSION

      - run:
          name: Install SonarCloud
          command: |
            apt-get update && apt-get install -y openjdk-11-jre
            dotnet tool install --global dotnet-sonarscanner
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet sonarscanner begin                                    \
              /k:"ar3cka_domainator"                                     \
              /d:sonar.host.url=https://sonarcloud.io                    \
              /o:ar3cka                                                  \
              /d:sonar.cs.opencover.reportsPaths="tests/**/coverage.xml" \
              /d:sonar.login=$SONAR_TOKEN

      - run:
          name: Update package version
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet gitversion /showconfig
            dotnet gitversion /updateassemblyinfo > version.json

      - run:
          name: Build
          command: |
            dotnet build -c=Release

      - run:
          name: Run unit tests
          command: |
              dotnet test tests/Domainator.UnitTests --no-build -c:Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
              dotnet test tests/Domainator.Demo.UnitTests --no-build -c:Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
              dotnet test tests/Domainator.Extensions.DependencyInjection.UnitTests --no-build -c:Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - run:
            name: Run integrartion tests
            command: |
              dotnet test tests/Domainator.Aws.IntegrationTests --no-build -c:Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - run:
          name: Create nuget packages
          command: |
            export PACKAGE_VERSION=`cat version.json | jq .NuGetVersionV2`
            dotnet pack --no-build -c:Release /p:PackageVersion=$PACKAGE_VERSION -o packages

      - persist_to_workspace:
          root: ./
          paths:
            - packages

      - run:
          name: Publish results to SonarCloud
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN

  publish:
      docker:
          - image: mcr.microsoft.com/dotnet/core/sdk:3.1.102-bionic
      steps:
          - attach_workspace:
                at: ./
          - run:
                name: Publish packages to Nuget.org
                command: |
                    for file in packages/*.nupkg; do dotnet nuget push $file -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json; done

orbs:
    jq: circleci/jq@1.5

workflows:
  version: 2
  build-package:
    jobs:
      - build:
          context: SonarCloud
      - publish:
          requires:
              - build
          context: Nuget
          filters:
            branches:
              ignore: master
